dot:
	dot -Tpng -o sw901e12.RecoveryOptionOne.executeRecovery__VCFG.png sw901e12.RecoveryOptionOne.executeRecovery__VCFG.dot
	dot -Tpng -o sw901e12.handlers.PEHSystemRecovery.handleAsyncEvent__VWCET_CallString.EMPTY_ALWAYS_MISS.png sw901e12.handlers.PEHSystemRecovery.handleAsyncEvent__VWCET_CallString.EMPTY_ALWAYS_MISS.dot
	dot -Tpng -o callgraph.png callgraph.dot
	dot -Tpng -o sw901e12.handlers.PEHSystemRecovery.handleAsyncEvent__VCFG.png sw901e12.handlers.PEHSystemRecovery.handleAsyncEvent__VCFG.dot
	dot -Tpng -o sw901e12.RecoveryOptionOne.executeRecovery__VWCET_CallString.EMPTY_ALWAYS_MISS.png sw901e12.RecoveryOptionOne.executeRecovery__VWCET_CallString.EMPTY_ALWAYS_MISS.dot
